version: 0.2
 
phases:
  pre_build:
    commands:
      - echo Building Config
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --no-include-email --region $AWS_REGION)
      - BUILD_ID=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c1-8)
      - echo Using BUILD_ID = $BUILD_ID
  build:
    commands:
      - echo Building Maven Project
      - mvn clean
      - mvn install
      - echo Build started on `date`
      - echo Building the Docker image...          
      - docker build -t $SERVICE_NAME:$BUILD_ID --build-arg JAR_FILE=config-server.jar --build-arg SPRING_ENV=$SPRING_ENV .
      - docker tag $SERVICE_NAME:$BUILD_ID $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPO_NAME:$BUILD_ID
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$SERVICE_NAME:$BUILD_ID
      - echo Writing image definitions file...
      - printf '[{"name":"%s","imageUri":"%s"}]' $SERVICE_NAME $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$SERVICE_NAME:$BUILD_ID > imagedefinitions.json
artifacts:
  files:
    - imagedefinitions.json
    - 'Dockerfile'
    - 'target/config-server.jar'