server:
  port: 8888
  servlet-path: /config/*

logging:
  level:
    org:
      springframework:
        web:
          servlet: DEBUG

spring:
  application:
    name: config
---
spring:
  profiles: local
  cloud:
    config:
      server:
        git:
          uri: https://github.com/revaturelabs/caliber-2-central-config-repo.git
eureka:
 client:
   service-url:
     defaultZone: http://localhost:8761/eureka
          
---
# (dev) development profile
spring:
  profiles: dev
  cloud:
    config:
      server:
        git:
          uri: https://github.com/revaturelabs/caliber-2-central-config-repo.git
eureka:
  client:
    enabled: false
---
# (prod) production profile
spring:
  profiles: prod
  cloud:
    config:
      server:
        git:
          uri: https://github.com/revaturelabs/caliber-2-central-config-repo.git
  
eureka:
 client:
   service-url:
     defaultZone: http://caliber-2-dev-alb-315997072.us-east-1.elb.amazonaws.com/eureka
 instance:
   leaseRenewalIntervalInSeconds: 30
   lease-expiration-duration-in-seconds: 60
   prefer-ip-address: true           

