server:
  port: 8888
  
eureka:
  client:
    service-url:
      default: 54.147.136.238:32820/eureka 
  instance:
    lease-expiration-duration-in-seconds: 2
    lease-renewal-interval-in-seconds: 1

spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/revaturelabs/caliber-2-central-config-repo.git
          
          